import numpy as np
import matplotlib.pyplot as plt

xc = np.fromfile('x.dat', dtype = np.float64)
yc  = np.fromfile('y.dat', dtype = np.float64)
u = np.fromfile('u_orig.dat', dtype = np.float64)
v = np.fromfile('v_orig.dat', dtype = np.float64)
upol = np.fromfile('u_pol.dat', dtype = np.float64)
vpol = np.fromfile('v_pol.dat', dtype = np.float64)
urec = np.fromfile('u_rec.dat', dtype = np.float64)
vrec = np.fromfile('v_rec.dat', dtype = np.float64)
divpol = np.fromfile('d_pol.dat', dtype = np.float64)
divrec = np.fromfile('d_rec.dat', dtype = np.float64)

u = u.reshape(yc.size, xc.size)
v = v.reshape(yc.size, xc.size)
upol = upol.reshape(yc.size, xc.size)
vpol = vpol.reshape(yc.size, xc.size)
urec = urec.reshape(yc.size, xc.size)
vrec = vrec.reshape(yc.size, xc.size)
divpol = divpol.reshape(yc.size, xc.size)
divrec = divrec.reshape(yc.size, xc.size)


plt.clf()
plt.contourf(xc, yc, u, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.title('u origional')
plt.colorbar()
#plt.show()
plt.savefig('u_original.png')

plt.clf()
plt.contourf(xc, yc, v, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.title('v origional')
plt.colorbar()
#plt.show()
plt.savefig('v_origional.png')

plt.clf()
plt.contourf(xc, yc, upol, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.colorbar()
plt.title('polluted u')
#plt.show()
plt.savefig('u_pol.png')

plt.clf()
plt.contourf(xc, yc, vpol, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.title('polluted v')
plt.colorbar()
#plt.show()
plt.savefig('v_pol.png')

plt.clf()
plt.contourf(xc, yc, urec, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.title('reconstructed u')
plt.colorbar()
#plt.show()
plt.savefig('u_rec.png')

plt.clf()
plt.contourf(xc, yc, vrec, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.title('reconstructed v')
plt.colorbar()
#plt.show()
plt.savefig('v_rec.png')



plt.clf()
plt.contourf(xc, yc, divpol, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.colorbar()
plt.title('div polluted u')
#plt.show()
plt.savefig('div_pol.png')

plt.clf()
plt.contourf(xc, yc, divrec, 255) 
#plt.grid(True)
plt.xlabel('x')
plt.ylabel('y') 
plt.colorbar()
plt.title('div recon u')
#plt.show()
plt.savefig('div_rec.png')


